version: "3.7"

x-server-environment:
  &server-environment
  - ConnectionString=Server=mssql;Initial Catalog=Vlad2020;User Id=sa;Password=${DB_PW}
  - ASPNETCORE_ENVIRONMENT=Development

services:
  Vlad2020.apps.api.base:
    environment: *server-environment

  Vlad2020.apps.api.web:
    environment: *server-environment
    ports:
      - "5002:80"

  Vlad2020.apps.identityserver.web:
    environment: *server-environment
    ports:
      - "6002:80"

  Vlad2020-angular-redux:    
    ports:
      - "4201:80"
